### ISSUE TITLE
InvalidCharacterError: Failed to execute 'add' on 'DOMTokenList': The token provided ('cke_source cke_reset cke_enable_context_menu')

### ISSUE THREAD

**Issue by darol100** [hectorguo/CKEditor-Markdown-Plugin#16]
Does not work with Drupal 8.
I'm trying to build a Drupal 8 module with this libraries and I run into this issue. `InvalidCharacterError: Failed to execute 'add' on 'DOMTokenList': The token provided ('cke_source cke_reset cke_enable_context_menu')`

<img width="1507" alt="screen shot 2016-03-21 at 3 00 00 am" src="https://cloud.githubusercontent.com/assets/6808460/13915316/2f4e7188-ef11-11e5-895f-9fed46d24a31.png">

**Comment by hectorguo** [comment]
This issue has been fixed [line #49](https://github.com/hectorguo/CKEditor-Markdown-Plugin/blob/master/markdown/plugin.js#L49).  If you download from github, it will work well.

**Comment by darol100** [comment]
I download it from Github and I still got the same issue.

**Comment by davidgiga1993** [comment]
Had the same issue. As it turns out, you can't use the "Basic Package" of CKEditor. You need the "Standard Package".
