### ISSUE TITLE
Uncaught InvalidCharacterError

### ISSUE THREAD

**Issue by Kikketer** [hectorguo/CKEditor-Markdown-Plugin#2]
Just having this one included in the standard CKEditor configuration and running their "samples" area.  When I switch to Markdown mode I get the following error:

````
Uncaught InvalidCharacterError: Failed to execute 'add' on 'DOMTokenList': The token provided ('cke_source cke_reset cke_enable_context_menu') contains HTML space characters, which are not valid in tokens.
````

Modifying line 49 (plugin.js) fixes the issue:

````
textarea.addClass('cke_source cke_reset cke_enable_context_menu'.split(' '));
````

**Comment by hectorguo** [comment]
just fixed it. 

You can update the `plugin.js`.

or just change line 49 to this:
```
textarea.addClass('cke_source').addClass('cke_reset').addClass('cke_enable_context_menu');
```

The previous code is referred to official samples of CKEditor plugins, but I am not sure if it has changed the method in new versions.

Thanks for your feedback.
