### ISSUE TITLE
Add bower support

### ISSUE THREAD

**Issue by deeg** [hectorguo/CKEditor-Markdown-Plugin#5]
It would be nice to be able to download this plugin through bower.

**Comment by hectorguo** [comment]
Good idea! Already added to bower.
```
bower install ckeditor-markdown-plugin
```

**Comment by cardosoccc** [comment]
@hectorguo, hi there! I'm trying to use both the ckeditor bower package together with the plugin bower package, but I still need to move the plugin directory to the ckeditor/plugin directory. Am I missing something? There is a way to avoid this manual handling?
