### ISSUE TITLE
Demo does not work

### ISSUE THREAD

**Issue by mihailik** [hectorguo/CKEditor-Markdown-Plugin#6]
Clicking on a DEMO link and getting a page with no editor

![screenshot from 2015-10-04 10 03 06](https://cloud.githubusercontent.com/assets/4041967/10267126/30f92bc0-6a7f-11e5-82c6-4ca77f66b5f7.png)

There are errors in F12 console too

![screenshot from 2015-10-04 10 05 00](https://cloud.githubusercontent.com/assets/4041967/10267130/6f464e76-6a7f-11e5-9552-f35a53c03ce2.png)

**Comment by hectorguo** [comment]
Thanks for your feedback. This issue has been fixed. You can refresh the demo page, and try again.
