### ISSUE TITLE
Error invoking markdown plugin

### ISSUE THREAD

**Issue by daxhns** [hectorguo/CKEditor-Markdown-Plugin#8]
Hi,

I get this error in the console after I click on the Markdown button in the editor:

Uncaught InvalidCharacterError: Failed to execute 'add' on 'DOMTokenList': The token provided ('cke_source cke_reset cke_enable_context_menu') contains HTML space characters, which are not valid in tokens.

I tracked it down to the line 49 in plugin.js:  textarea.addClass('cke_source cke_reset cke_enable_context_menu');

**Comment by daxhns** [comment]
Sorry about this, i see that this has already been resolved in the latest code.

BTW, i first downloaded plugin from ckeditor site, which still has this bug.

**Comment by jjozsi** [comment]
The plugin from the ckeditor still has the bug (updated 9th August).

**Comment by tablatronix** [comment]
:+1:

**Comment by hectorguo** [comment]
Sorry about that, not maintain it on ckeditor website for a long time. 
I will decide to fix some of issues recently.

**Comment by Haikuch** [comment]
version on ckeditor.com still seems to be not working?!

**Comment by promoia** [comment]
I changed this line 49 
textarea.addClass('cke_source').textarea.addClass('cke_reset').textarea.addClass('cke_enable_context_menu');  

to 3 line, then it works :) 
textarea.addClass('cke_source');
textarea.addClass('cke_reset');
textarea.addClass('cke_enable_context_menu');  

Don't know why, but worked for me

**Comment by 5663015** [comment]
> I changed this line 49
> textarea.addClass('cke_source').textarea.addClass('cke_reset').textarea.addClass('cke_enable_context_menu');
> 
> to 3 line, then it works :)
> textarea.addClass('cke_source');
> textarea.addClass('cke_reset');
> textarea.addClass('cke_enable_context_menu');
> 
> Don't know why, but worked for me

Thanks very much for your solution! I have the same problem, now it is OK.
